### ISSUE TITLE
[BUG] Frame skip on turret placement

### ISSUE THREAD

**Issue by ReflextionsDev** [ReflextionsDev/Zombiehood#141]
**Describe the bug**
Frame skip on turret placement, not seamless

**Comment by Everade** [comment]
I noticed that in the code there are some unique animation calls for placements. I started doing the same exception for the turret as i also noticed this non-seamless animation. Which was btw also the cause for turrets not spawning properly. However the code still has that extra turret exception implemented right now, but i may have missed something there as it didn't work properly before as you noticed. So either we could improve the turret spawn animation to allign with the placement animation, or create a unique turret placement animation which is somewhat prepared already, and wouldn't interfere with despawning.

**Comment by ReflextionsDev** [comment]
OK interesting, I think it was seamless before so it may just be on the wrong frame.
