### ISSUE TITLE
Throwable sprites get stretched

### ISSUE THREAD

**Issue by Everade** [ReflextionsDev/Zombiehood#24]
There are a lot of cases in which a Kunai gets stretched in length and width after hitting/killing an enemy.
Additionally, most of the time Kunais do not stick to the body part they hit, instead they align with the feet/floor. This also seems to depend on the current enemy animation frame.

![image](https://github.com/ReflextionsDev/Zombiehood/assets/12261601/d82c5112-42e4-4b5a-ac57-0e0686327d67)
https://github.com/ReflextionsDev/Zombiehood/assets/12261601/98a94ef7-26a1-441f-800f-feb38655c216

**Comment by ReflextionsDev** [comment]
This is a global issue with projectiles of this type, having a fix would be good, but will involve setting up A LOT of image points across a lot of animations. Additionally would be nice to have different animations for enemy stuck and enviornmental stuck (blood vs no blood)
