### ISSUE TITLE
Weapon hotspots are incorrect on overworld

### ISSUE THREAD

**Issue by ReflextionsDev** [ReflextionsDev/Zombiehood#28]
Except pistol, all other weapon types seem to be affected

**Comment by ReflextionsDev** [comment]
Should be an easy fix just need to reference the hotspots like the player sprite does on levels

**Comment by ReflextionsDev** [comment]
Not a huge deal but it's been in forever and pretty obvious

**Comment by Everade** [comment]
@ReflextionsDev 
Not sure what you mean with hotspots. The only bug i've noticed were that the second arm is missing on the overworld if you equipped a dual weapon.

**Comment by ReflextionsDev** [comment]
Some examples:

![Screenshot 2024-08-26 at 11 58 04 PM](https://github.com/user-attachments/assets/bd2ffad2-d395-4927-bb53-47f0889bb219)
![Screenshot 2024-08-26 at 11 53 49 PM](https://github.com/user-attachments/assets/64a13009-399d-42cb-b797-fee63af76e1b)
![Screenshot 2024-08-26 at 11 54 29 PM](https://github.com/user-attachments/assets/70575aeb-e71e-4300-a9fc-ab02105dc23c)
![Screenshot 2024-08-26 at 11 55 27 PM](https://github.com/user-attachments/assets/02b3a817-76c7-45b9-990e-e351814f3499)

Make sure each type (launcher not shown) is supported. Rifle looks correct here so maybe it's using the same animation hotspot as the pistol? I recommend using debug mode to cycle through player_arm animations here cause playing through each level will be a hassle. I'll also open another issue for the dual weapon not appearing.

**Comment by ReflextionsDev** [comment]
More info: player arms are using a specific animation hotspot on the player sprite animation in game. Looks like they're all using the pistol on the overworld. 
![Screenshot 2024-08-26 at 11 57 19 PM](https://github.com/user-attachments/assets/3ce172c8-10a3-4281-b6da-83fcd5a47fd9)
