### ISSUE TITLE
[Weapon] Reload issue

### ISSUE THREAD

**Issue by Everade** [ReflextionsDev/Zombiehood#49]
When you fire the last rounds from a weapon and then switch to another weapon that uses the same ammo but doesn't have a full magazine, attempting to reload will cause the game to switch your current weapon to the base pistol, even though there are still bullets left in the magazine.

**Comment by ReflextionsDev** [comment]
Does the player have any reserve ammo or just the mag? If it's just the mag then this would be the intended behavior as there is no ammo to reload from so it will auto switch.

**Comment by ReflextionsDev** [comment]
0 ammo left in inventory.
2 guns, one with empty mag.
another gun still bullets in mag.

Now when you reload on the empty gun, it will remind that variable state as empty.
Now if you switch back to the gun that has still ammo, and reload, it will swap it, because the variable state was kept.
