### ISSUE TITLE
[Gamepad] Cursor navigation hard-lock

### ISSUE THREAD

**Issue by Everade** [ReflextionsDev/Zombiehood#51]
There are certain edge cases in which, when you get back from a level to the Overworld screen, or the "Game" menu, the cursor can become hard-locked. The only way to get your cursor to move again is by using your mouse, then go back using the gamepad.

**Comment by Everade** [comment]
It specifically seems to fail due to the new "AimAssist_Active = 0" condition that was added to the cursor navigation actions.
Because this variable seems to remain on during certain cases, as such you can no longer move the cursor.
![image](https://github.com/user-attachments/assets/37fc0016-5b30-438e-bc61-f754bf60e8ef)

**Comment by ReflextionsDev** [comment]
@Everade Did I add that or you? I was experimenting with this but think I had undone it.

**Comment by Everade** [comment]
> @Everade Did I add that or you? I was experimenting with this but think I had undone it.
This was part of your https://github.com/ReflextionsDev/Zombiehood/pull/46
I haven't touched anything related to aim assist so far.

If the aim assist cursor positioning occurs after the cursor runtime, these conditions can likely be removed. Alternatively, we could deactivate the cursor runtime group entirely during aim assist gameplay, as the cursor runtime is used exclusively for UI purposes.
