### ISSUE TITLE
Money has a square shaped effect

### ISSUE THREAD

**Issue by Everade** [ReflextionsDev/Zombiehood#60]
When money loot flies towards the player character, it has a square-shaped opaque effect overlay, which appears out of place.
![image](https://github.com/user-attachments/assets/90a2e98f-368c-4230-a5a7-0c180b10b8ce)

**Comment by ReflextionsDev** [comment]
Not sure I understand the report, the particles are spinning so the shape does change. All loot particles have a glow effect I believe.

**Comment by ReflextionsDev** [comment]
Ohh those are supposed to be bill not coins.. maybe we can replace with coins later but I do like the green as it contrasts with ammo which is orange
