### ISSUE TITLE
Glove duplicates (Unstackable Artifacts)

### ISSUE THREAD

**Issue by Everade** [ReflextionsDev/Zombiehood#95]
Glove types that you've already obtained can be dropped again, but also obtained again while not giving any benefits.
They should either not drop again once obtained, or the player should not be able to pick them up again, so instead they could be scrapped for money.

**Comment by ReflextionsDev** [comment]
This actually a design issue I've struggled with:

I really like having artifacts be stackable, and it's sort of an anti-pattern to have 1 time style artifacts like this that can't stack.  But I also like having these items that have one off effects. (Artifacts apply to starter pistol for example).

There's a few options I'm tossing around:
- A separate type of artifact that has a separate inventory area so you can tell that it's unstackable
- Simply remove the item from the artifact pool
- Duplicate unstackable artifacts are re-rolled or converted to cash (as you pointed out well)

Probably the best option for now will be to just remove it from the pool... 

But I also like the idea of splitting it out into a new inventory pool, maybe runes or charms or something. But let's table that cause scope creep.

**Comment by ReflextionsDev** [comment]
Solutions:
- [ ] Create an artifact stackable bool (if there isn't one already)
- [ ] Once an unstackable artifact is equipped, remove it from the spawn pool for the run
- [ ] Prevent player from picking up already equipped artifacts (in case 2 are initted)
